### ISSUE TITLE
AttributeError: type object 'ScanItem' has no attribute 'bind'

### ISSUE THREAD

**Issue by 8a8al00ey** [by275/plex_autoscan#15]
DB refactoring throws and error on startup.

```
Oct  7 08:50:07 sb systemd[1]: Started Plex Autoscan.
Oct  7 08:50:08 sb python3[2576]: #033[30;1m2022/10/07 08:50:08#033[0m #033[33;1mWARNI#033[0m #033[35mDB    #033[0m #033[30;1mMainThread#033[0m You are using an in-memory database as Autoscan queue. Consider using a file-based one by specifying `--queuefile` arg in CLI.
Oct  7 08:50:08 sb python3[2576]: Traceback (most recent call last):
Oct  7 08:50:08 sb python3[2576]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Oct  7 08:50:08 sb python3[2576]:     return _run_code(code, main_globals, None,
Oct  7 08:50:08 sb python3[2576]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Oct  7 08:50:08 sb python3[2576]:     exec(code, run_globals)
Oct  7 08:50:08 sb python3[2576]:   File "/opt/plex_autoscan/autoscan/__main__.py", line 426, in <module>
Oct  7 08:50:08 sb python3[2576]:     main()
Oct  7 08:50:08 sb python3[2576]:   File "/opt/plex_autoscan/autoscan/__main__.py", line 419, in main
Oct  7 08:50:08 sb python3[2576]:     process_menu(conf.args["cmd"])
Oct  7 08:50:08 sb python3[2576]:   File "/opt/plex_autoscan/autoscan/__main__.py", line 398, in process_menu
Oct  7 08:50:08 sb python3[2576]:     ScanItem.init(conf.settings["queuefile"])
Oct  7 08:50:08 sb python3[2576]:   File "/opt/plex_autoscan/autoscan/db.py", line 40, in init
Oct  7 08:50:08 sb python3[2576]:     cls.bind(database)
Oct  7 08:50:08 sb python3[2576]: AttributeError: type object 'ScanItem' has no attribute 'bind'
```

**Comment by 8a8al00ey** [comment]
Sorry peewee was really old. After updating to latest it started working
